function expand (keyb) {if(Array.isArray(keyb)) return keyb.join(', '); else return keyb;};

exports.titleMessages = {
    invalidCharpage  : "Not valid Char Page window!",
    loadingCharpage  : "Loading Char Page...",
    buildingCharpage : "Building scenario. Please wait some seconds...",
    cpDone           : "DONE! Saved CP in Screenshot folder",
    doneSavedAs      : "Done! Saved as ",
    recording        : "RECORDING",
    alreadyRecording : "You are already recording another window!"
}

exports.charPageStudioMessages = {
    locale: 'en-US', title: 'AquaStar — Char Page Studio', heading: 'Char Page Studio',
    description: 'Customize a Char Page with the native Flash Player.', sceneModeLabel: 'Scene mode',
    charPageMode: 'Char Page Studio', emptySceneMode: 'Empty scene',
    emptySceneHint: 'Empty scene uses the new AQW compositor: without the Char Page interface, border, or background.',
    characterLabel: 'AQW character', loadCharacterButton: 'Load from Char Page',
    characterHint: 'Uses the character configured in Settings by default, but does not download anything until this button is used.',
    colorsLabel: 'Colors', backgroundIndexLabel: 'Background (bgindex)', emptySceneSettingsLabel: 'Solid background and FPS (empty scene)',
    solidBackgroundLabel: 'Solid background', nativeFps: '24 FPS (AQW)', loadSceneButton: 'Load scene', savePngButton: 'Save PNG screenshot', saveGifButton: 'Generate GIF (8 s)'
}

exports.dialogMessages = {
    helpTitle   :'Help:',
    helpMessage :"These are the keybindings added to the game.",
    helpDetail(k) {return expand(k.wiki) + ' - AQW Wiki\n' +
        expand(k.design)    + ' - AQW Design notes\n' +
        expand(k.account)   + ' - Account page\n' +
        expand(k.charpage)  + ' - Character (Player) lookup. You can also just use the in-game lookup.\n' +
        expand(k.cpSshot)   + ' - (Char pages only!) Take a screenshot of the current char page.\n' +
        expand(k.newAqw)    + ' - Opens a new instance.\n' +
        expand(k.newTest)   + ' - Opens a Testing AQW instance.\n' +
        expand(k.about)     + ' - About AquaStar.\n' +
        expand(k.fullscreen)+ ' - Toggles Fullscreen\n' +
        expand(k.sshot)     + ' - Screenshot the game window (AQW and AQLITE only). They are saved in another folder as detailed below.\n' +
        expand(k.record)    + ' - Record the Game Screen. Use it again to stop.\n' +
        expand(k.reload)    + " - Reload the pages, like in a browser\n" +
        expand(k.reloadCache)+' - Clears all game cache, some cookies and refresh the window (can fix some bugs in game)\n' +
        expand(k.settings)  + ' - Opens the Settings screen, to customize keybindings.\n' +
        expand(k.reminders) + ' - Opens the Reminders screen, to track daily/weekly quests per character.\n\n' +
        'For an older/custom aqlite file, please name it "aqlite_old.swf" and put it in the same folder as the executable, as said below!\n\n' +
        'Note:' + expand(k.help) + ' Shows this message.';
    },
    helpScreenshot     : "Screenshot folder: ",
    helpAqliteOld      : "App folder for aqlite_old and aquastar.json (can change if user move the application): ",
    helpCustomKeyPath  : "Another Location for aquastar.json with custom keybindings. Check Readme.md for help: ",
    
    aboutTitle     : "About AquaStar Version: ",
    aboutMessage   : "Aquastar would not be possible without the help of:",
    aboutDetail    : 
        '133spider (github) for creating AQLite itself\n' +
        'aquaspy (github)\n' +
        'biglavis (github) For developing the extension WikiView\n' +
        'Artix Entertainment (artix.com)\n' +
        'ElectronJs (electronjs.org)\n' +
        'Adobe Flash Player (adobe.com)\n' +
        'YOU! (Yes, You! Thanks for supporting us!)\n\n' +
        'Note: This is NOT an official Artix product. Artix Entertainment does not recommends it by any means. You are at your own risk using it.\n\n' +
        'You can give your opinion, contribute and follow the project here: ',
    aboutDebug     : "Debug Info",
    
    aboutGithubPrompt : "AquaStar Releases page",
    aboutClosePrompt  : "Close this Popup"
}

exports.menuMessages = {
    menuBackward     : "Backward",
    menuFoward       : "Foward",
    menuOtherPages   : "Usefull Pages",
    menuOtherPages2  : "Other usefull Pages",
    menuSocialMedia  : "Social Media",
    menuWiki         : "AQW Wiki",
    menuDesign       : "Design Notes",
    menuBalancePatchNotes: "Balance/Class Patch Notes",
    menuAccount      : "AQW Account",
    menuPortal       : "Portal Battleon",
    menuHeromart     : "Heromart",
    menuDailyGifts   : "Daily Drops",
    menuCalendar     : "Calendar of Events",
    menuCharpage     : "Charpages",
    menuForge        : "Forge Enchants",
    menuReddit       : "AQW Subreddit",
    menuTwitter      : "Alina's Twitter",
    menuTakeShot     : "Take a SShot of CP (CP ONLY!)",
    menuCharPageStudio: "Char Page Studio",
    menuCopyURL      : "Copy this page's URL",
    menuReloadPage   : "Reload this page",
    menuSettings     : "Settings",
    menuReminders    : "Reminders",
    menuTodo         : "To-Do List",
    menuInventory    : "Inventory",
    menuStrategy     : "Strategy"
}

exports.settingsMessages = {
    title            : "AquaStar - Settings",
    heading          : "Keybind Settings",
    description      : "Click \"Record\" and press a new key combination to change a shortcut. Changes are saved to the file shown below and require restarting AquaStar to take effect.",
    saveLocationLabel: "Saving to: ",
    saveButton       : "Save Changes",
    resetAllButton   : "Reset All to Default",
    restartButton    : "Restart AquaStar Now",
    closeButton      : "Close",
    recordButton     : "Record",
    recordingLabel   : "Press keys... (Esc to cancel)",
    resetButton      : "Reset",
    savedMessage     : "Saved! Restart AquaStar to apply the new keybindings.",
    macOnlyLabel     : " (macOS only)",
    charpageOnly     : " (char page only)",
    labels: {
        wiki:        "Open AQW Wiki",
        account:     "Open Account Page",
        design:      "Open Design Notes",
        charpage:    "Character Lookup",
        newAqw:      "Open New AQW Instance",
        newTest:     "Open Testing AQW Instance",
        about:       "About AquaStar",
        fullscreen:  "Toggle Fullscreen",
        sshot:       "Screenshot Game Window",
        cpSshot:     "Screenshot Char Page",
        reload:      "Reload Page",
        reloadCache: "Reload and Clear Cache",
        dragon:      "Open DragonFable",
        forward:     "Go Forward",
        backward:    "Go Backward",
        help:        "Show Help",
        settings:    "Open Settings (this screen)",
        reminders:   "Open Reminders",
        todo:        "Open To-Do List",
        inventory:   "Open Inventory",
        strategy:    "Open Strategy",
        record:      "Record Game Screen"
    },
    optionsHeading: "Other Options",
    optionLabels: {
        playerCharacter:   "Player Character",
        featurePlayerName: "Show Player Character in Window Title",
        customUrl:         "Custom Game URL",
        recordingFormat:   "Recording Format",
        renderMode:        "Flash Renderer",
        ruffleUpdateChannel: "Ruffle Update Channel",
        ruffleAutoUpdate:  "Automatically download updates",
        autoSync:          "Auto Sync Inventory",
        enableDevTools:    "Enable DevTools"
    },
    optionHints: {
        playerCharacter:   "Letters and numbers only. Used by the Char Page shortcut (Alt+P) to open straight to this character.",
        featurePlayerName: "When on, replaces \"AquaStar\" in the main window title with your Player Character above.",
        customUrl:         "Loads a different SWF/game URL instead of the default AQW game. Leave empty for the default. Ignored if a custom SWF file (below) is active.",
        recordingFormat:   "File format used when recording the game screen (Ctrl+J). MP4 isn't available on this Electron version.",
        renderMode:        "Which Flash runtime loads AQW (main, new instance, Testing) and DragonFable (Alt+1). The Char Page is unaffected (Artix already uses Ruffle there).",
        ruffleUpdateChannel: "Latest uses Ruffle's most recent stable release. Nightly includes newer experimental changes. To apply a channel change, fully close AquaStar and open it again; do not use only the Restart button.",
        ruffleAutoUpdate:  "Checks the selected channel in the background every time AquaStar opens. A download is applied after restart.",
        autoSync:          "Periodically syncs your Inventory/BuyBack data from account.aq.com in the background (about every 2 hours) once you've logged in there at least once via Alt+A. When off, sync only happens when you use a Sync Now button (in the Inventory window or on account.aq.com/Home).",
        enableDevTools:    "Opens the DevTools console automatically on startup."
    },
    customSwfHeading      : "Custom SWF File",
    customSwfLabel        : "Local SWF File",
    customSwfHint         : "Overrides the default AQW game entirely with a local .swf file - takes priority over the Custom Game URL option above. Takes effect after restarting AquaStar.",
    customSwfActiveLabel  : "Active: ",
    customSwfInactiveLabel: "Not set - using the default AQW game.",
    customSwfChooseButton : "Choose File...",
    customSwfRemoveButton : "Remove",
    customSwfRemoveConfirm: "Remove the custom SWF file? AquaStar will go back to loading the default AQW game after a restart.",
    customSwfChosenMessage: "Custom SWF file set. Restart AquaStar to use it.",
    customSwfRemovedMessage: "Custom SWF file removed. Restart AquaStar to apply.",
    ruffleHeading          : "Ruffle Updates",
    ruffleStatusLabel      : "Ruffle selected at startup",
    ruffleLoadedLabel      : "Selected at startup: ",
    ruffleConfiguredChannelLabel: "Configured update channel: ",
    ruffleLatestLabel      : "Latest (Stable)",
    ruffleNightlyLabel     : "Nightly (Experimental)",
    ruffleFallbackLabel    : "Bundled fallback: ",
    ruffleInactiveLabel    : "Ruffle is not active; Flash Player is selected.\n",
    ruffleDownloadedLabel  : "Downloaded version",
    ruffleBundledLabel     : "Bundled fallback",
    ruffleUpdateLabel      : "Update Ruffle",
    ruffleUpdateHint       : "Downloads the self-hosted web build for the selected channel from Ruffle's official GitHub release. Stable is recommended; Nightly is experimental. Restart to apply it.",
    ruffleUpdateButton     : "Download Update",
    ruffleDownloadingMessage: "Downloading Ruffle update...",
    ruffleUpdatedMessage   : "Ruffle update downloaded. Restart AquaStar to apply it.",
    ruffleAlreadyCurrentMessage: "Ruffle is already up to date.",
    ruffleBundledAlreadyCurrentMessage: "The bundled Ruffle is already the latest stable version.",
    ruffleUpdateFailedMessage: "Could not update Ruffle: ",
    ruffleRestoreLabel     : "Restore bundled Ruffle",
    ruffleRestoreHint      : "Removes downloaded Ruffle files at the next restart and uses the version packaged with AquaStar.",
    ruffleRestoreButton    : "Restore Bundled Version",
    ruffleRestoreConfirm   : "Restore the Ruffle version packaged with AquaStar? Downloaded Ruffle files will be removed after restart.",
    ruffleRestoreMessage   : "Bundled Ruffle will be restored when AquaStar restarts.",
    optionWarnings: {
        renderMode:     "Ruffle is an experimental, open-source Flash emulator. It may be slower, less stable, or behave differently than the real Flash Player, especially in crowded rooms. Switch anyway?",
        enableDevTools: "This option is for developers. Normal players usually don't need it. Enable anyway?"
    }
}

exports.remindersMessages = {
    title              : "AquaStar - Reminders",
    heading            : "Reminders",
    description        : "Track daily and weekly in-game tasks per character. Resets follow the AE server clock (America/New_York) - daily at midnight, weekly at the Thursday-to-Friday midnight.",
    showCompletedLabel : "Show completed",
    showMemberDailiesLabel: "Show member reminders",
    individualHiddenLabel: "Individual hidden list per character",
    serverTimeLabel    : "Server Time",
    categoryClassLabel : "Class",
    categoryUltraLabel : "Ultra Bosses",
    categoryOtherLabel : "Other",
    memberToggleLabel  : "Member",
    memberBadgeShort   : "★",
    memberBadgeTitle   : "Member-only content",
    seasonalToggleLabel: "Seasonal",
    seasonalSectionLabel: "Seasonal",
    nextFriday13Label  : "Next Friday the 13th: ",
    thisMonthLabel     : "This Month",
    monthNames: [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    ],
    seasonalEvents: {
        nulgathBirthday: { label: "Nulgath's Birthday (Jan)",                       short: "JAN" },
        carnival:        { label: "Carnival / Lunar New Year (Feb)",                short: "FEB" },
        dageBirthday:    { label: "Dage's Birthday / Good Luck Day (Mar)",          short: "MAR" },
        aprilFools:      { label: "April Fools (Apr)",                              short: "APR" },
        mayThe4th:       { label: "May the 4th (May)",                              short: "MAY" },
        starFestival:    { label: "Star Festival / Summer (Jul)",                   short: "JUL" },
        kalaSeason:      { label: "Back to School / Indonesian Day (Aug)",          short: "AUG" },
        friday13:        { label: "Friday the 13th",                                short: "F13" },
        pirateDay:       { label: "Talk Like a Pirate Day / Independence (Sep)",    short: "SEP" },
        anniversary:     { label: "Mogloween / AQW Anniversary (Oct)",              short: "OCT" },
        blackFriday:     { label: "Black Friday (Nov)",                             short: "NOV" },
        frostval:        { label: "Frostval / New Year (Dec)",                      short: "DEC" }
    },
    addCharacterTab    : "+ Add Character",
    promptCharacterName: "Character name:",
    promptOkButton     : "OK",
    promptCancelButton : "Cancel",
    baseCharacterPrompt: "Which character's hidden list should become the new shared one?",
    confirmDeleteCharacter: "Remove this character and its progress on every quest? This cannot be undone.",
    confirmDeleteQuest : "Delete this quest for every character? This cannot be undone.",
    noCharactersHint   : "Add a character tab above to start tracking quests.",
    questNamePlaceholder: "Quest name",
    questJoinPlaceholder: "/join ...",
    filterNamePlaceholder: "Filter by name...",
    filterAllLabel     : "All",
    dailyLabel         : "Daily",
    weeklyLabel        : "Weekly",
    monthlyLabel       : "Monthly",
    addQuestButton     : "Add Quest",
    copyButton         : "Copy",
    copiedLabel        : "Copied!",
    deleteButton       : "Delete",
    hideButton         : "Hide",
    unhideButton       : "Unhide",
    archiveToggleLabel : "Hidden",
    dragHandleTitle    : "Drag to reorder",
    renameTabTitle     : "Rename",
    removeTabTitle     : "Remove",
    savingLabel        : "Saving...",
    savedLabel         : "Saved"
}

exports.todoMessages = {
    title              : "AquaStar - To-Do List",
    heading            : "To-Do List",
    description        : "Track drops, shop items, and quest rewards to grab, per character.",
    serverTimeLabel    : "Server Time",
    individualHiddenLabel: "Individual completed list per character",
    categoryDropLabel  : "Drop",
    categoryDailyDropLabel: "Daily Drop",
    categoryShopMergeLabel: "Shop/Merge",
    categoryQuestRewardLabel: "Quest Reward",
    categoryHardFarmLabel: "Hard Farm",
    categoryReputationFarmLabel: "Reputation Farm",
    priorityToggleLabel: "Priority",
    priorityToggleTitle: "Toggle priority - priority tasks are listed first",
    seasonalToggleLabel: "Seasonal",
    seasonalSectionLabel: "Seasonal",
    nextFriday13Label  : "Next Friday the 13th: ",
    thisMonthLabel     : "This Month",
    monthNames: [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    ],
    seasonalEvents: {
        nulgathBirthday: { label: "Nulgath's Birthday (Jan)",                       short: "JAN" },
        carnival:        { label: "Carnival / Lunar New Year (Feb)",                short: "FEB" },
        dageBirthday:    { label: "Dage's Birthday / Good Luck Day (Mar)",          short: "MAR" },
        aprilFools:      { label: "April Fools (Apr)",                              short: "APR" },
        mayThe4th:       { label: "May the 4th (May)",                              short: "MAY" },
        starFestival:    { label: "Star Festival / Summer (Jul)",                   short: "JUL" },
        kalaSeason:      { label: "Back to School / Indonesian Day (Aug)",          short: "AUG" },
        friday13:        { label: "Friday the 13th",                                short: "F13" },
        pirateDay:       { label: "Talk Like a Pirate Day / Independence (Sep)",    short: "SEP" },
        anniversary:     { label: "Mogloween / AQW Anniversary (Oct)",              short: "OCT" },
        blackFriday:     { label: "Black Friday (Nov)",                             short: "NOV" },
        frostval:        { label: "Frostval / New Year (Dec)",                      short: "DEC" }
    },
    addCharacterTab    : "+ Add Character",
    promptCharacterName: "Character name:",
    promptOkButton     : "OK",
    promptCancelButton : "Cancel",
    baseCharacterPrompt: "Which character's completed list should become the new shared one?",
    confirmDeleteCharacter: "Remove this character and its progress on every task? This cannot be undone.",
    confirmDeleteTask  : "Delete this task for every character? This cannot be undone.",
    noCharactersHint   : "Add a character tab above to start tracking tasks.",
    taskNamePlaceholder: "Task name",
    wikiLinkPlaceholder: "Wiki link (optional)",
    joinCommandPlaceholder: "/join ... (optional)",
    copyButton         : "Copy",
    copiedLabel        : "Copied!",
    filterNamePlaceholder: "Filter by name...",
    filterAllLabel     : "All",
    addTaskButton      : "Add Task",
    wikiLinkButtonTitle: "Open wiki link",
    completeButton     : "Complete",
    reopenButton       : "Reopen",
    deleteButton       : "Delete",
    completedToggleLabel: "Completed",
    dragHandleTitle    : "Drag to reorder",
    renameTabTitle     : "Rename",
    removeTabTitle     : "Remove",
    savingLabel        : "Saving...",
    savedLabel         : "Saved"
}

exports.strategyMessages = {
  title: "AquaStar - Strategy",
  heading: "Strategy",
  description: "Plan team compositions, tactics and timed mechanics for Ultra and Challenge bosses.",
  addBoss: "Add Boss",
  manageClasses: "Classes",
  managePotions: "Potions",
  manageTimerTypes: "Timer Types",
  saved: "Saved",
  emptyBosses: "No bosses yet. Add one to begin planning.",
  emptyStrategies: "No strategies yet.",
  ultra: "Ultra Boss",
  challenge: "Challenge Boss",
  weekly: "Weekly",
  daily: "Daily",
  players: "players",
  zone: "Zone",
  noJoin: "No /join set",
  main: "Boss",
  left: "Left",
  right: "Right",
  open: "Open",
  edit: "Edit",
  delete: "Delete",
  deleteBossConfirm: "Delete this boss and all of its strategies?",
  deleteStrategyConfirm: "Delete this strategy?",
  bosses: "All Bosses",
  strategies: "Strategies",
  addStrategy: "Add Strategy",
  editStrategy: "Edit Strategy",
  team: "Team Composition",
  bossNotes: "Boss Details",
  strategyNotes: "Strategy Details",
  save: "Save",
  player: "Player",
  noClass: "No class selected",
  editBoss: "Edit Boss",
  name: "Name",
  join: "/Join command",
  reset: "Reset",
  kind: "Boss type",
  role: "Role",
  cancel: "Cancel",
  close: "Close",
  add: "Add",
  timers: "Timers",
  intro: "Intro (runs once)",
  loop: "Loop (repeats)",
  addTimer: "Add Timer",
  delay: "Delay (seconds)",
  timerType: "Effect",
  target: "Target",
  assignment: "Assignment",
  timerLabel: "Note",
  timerRunner: "Live Timer",
  startTimer: "Start Timer",
  stopTimer: "Stop Timer",
  timerIdle: "Ready — start the timer to run this strategy.",
  shortcut: "Global toggle shortcut (while this strategy is open)",
  shortcutError: "Shortcut unavailable",
  potionKind: "Potion category",
  tonic: "Tonic",
  elixir: "Elixir",
  potion: "Potion",
  timerRoles: "Timer Roles",
  timerRolesHelp: "Each role has its own first-action offset and repeat interval. The action happens when its bar reaches the end.",
  addRole: "Add role",
  showRoles: "Show roles",
  all: "All",
  none: "None",
  bestTonic: "Best tonic",
  bestElixir: "Best elixir",
  noPreference: "No preference",
  saveClass: "Save class",
  generalBossInfo: "General boss information",
  generalBossInfoHint: "Shown read-only in this boss strategies",
  consumables: "Consumables",
  consumablesFor: "Consumables for",
  noFavoriteConsumables: "No favorite tonic or elixir configured for this class.",
  noConsumablesInInventory: "None of this class consumables are in the synced inventory.",
  actionIn: "Action in",
  functionLabel: "Function",
  roles: {
    support: "Support",
    dps: "DPS",
    tank: "Tank",
    dot: "Damage over Time (DoT)"
  }
}

exports.inventoryMessages = {
  title: "AquaStar - Inventory",
  heading: "Inventory",
  description: "Browse your synced account.aq.com Inventory and BuyBack data, per character.",
  inventoryTabLabel: "Inventory",
  buyBackTabLabel: "Buy Back",
  syncButton: "Sync Now",
  syncingLabel: "Syncing...",
  syncedLabel: "Last synced: ",
  justNowLabel: "just now",
  neverSyncedLabel: "Never synced",
  syncErrorUnauthenticated: "Not logged in. Open the Account Page (Alt+A) and log in, then try again.",
  syncErrorNetwork: "Could not reach account.aq.com. Check your connection and try again.",
  filterNamePlaceholder: "Search items...",
  filterTypeAll: "All Types",
  filterAllLabel: "All",
  filterBankLabel: "Bank only",
  filterInventoryOnlyLabel: "Inventory only",
  filterMemberLabel: "Member only",
  filterNonMemberOnlyLabel: "Non-member only",
  filterAcLabel: "AC only",
  filterNonAcLabel: "Non-AC only",
  emptyStateLabel: "No items found. Try syncing or adjusting filters.",
  noCharactersLabel: "No characters synced yet. Log in via Alt+A, then Sync Now.",
  columnName: "Name",
  columnType: "Type",
  columnCount: "Count",
  columnBank: "Bank",
  columnAdded: "Added",
  columnCost: "Cost",
  columnRarity: "Rarity",
  columnInserted: "Sold",
  bankBadge: "Bank",
  inventoryBadge: "Inventory",
  acBadge: "AC",
  normalBadge: "Normal",
  filterLabels: "Labels",
  labelsSelected: "selected",
  labelFilterClear: "Clear",
  manageLabels: "Manage Labels",
  labelName: "Label name",
  addLabel: "Add",
  saveLabel: "Save",
  assignLabels: "Assign Labels",
  labelScopeCharacter: "This character",
  labelScopeGlobal: "All characters",
  labelScopeCharacterHint: "Only applies to the active character.",
  labelScopeGlobalHint: "Applies to the same item for every character.",
  assignLabelsHint: "The label scope is defined when it is created. Character labels are independent for each character; global labels always apply to everyone.",
  delete: "Delete",
  close: "Close",
  cancel: "Cancel",
  itemCountLabel: "{shown} of {total} items"
}

exports.wikiMessages = {
    mergeMaterialsTitle: "AquaStar: Shop materials",
    mergeDependencies: "Include dependencies",
    mergeBuyback: "Dependencies with Buy Back",
    mergeEmpty: "No materials listed.",
    mergeReputationLabel: "Reputation required:",
    mergeSelectAll: "Select all",
    mergeClearAll: "Clear all",
    mergeSelectItem: "Select item"
}
