function expand (keyb) {if(Array.isArray(keyb)) return keyb.join(', '); else return keyb;};

exports.titleMessages = {
    invalidCharpage  : "Janela de Char Page inválida",
    loadingCharpage  : "Carregando Char Page...",
    buildingCharpage : "Construindo cenário. Por favor aguarde uns segundos...",
    cpDone           : "PRONTO! Salvo a CP na pasta de Screenshots",
    doneSavedAs      : "Pronto! Salvo como ",
    recording        : "GRAVANDO",
    alreadyRecording : "Você já está gravando em alguma outra janela!"
}

exports.dialogMessages = {
    helpTitle   :'Ajuda:',
    helpMessage : "Estas são as keybindings adicionadas ao jogo.",
    helpDetail(k) {return expand(k.wiki) + ' - AQW Wiki\n' +
        expand(k.design)    + ' - AQW Design notes\n' +
        expand(k.account)   + ' - Account page\n' +
        expand(k.charpage)  + ' - Character (Player) lookup. Você também pode utilizar o interno do jogo.\n' +
        expand(k.cpSshot)   + ' - (Apenas char pages!) Printa a tela do char page atual.\n' +
        expand(k.newAqw)    + ' - Abre uma nova instância do AQW.\n' +
        expand(k.newTest)   + ' - Abre uma instância de testes do AQW.\n' +
        expand(k.about)     + ' - Sobre AquaStar.\n' +
        expand(k.fullscreen)+ ' - Ativa/Desativa Fullscreen\n' +
        expand(k.sshot)     + ' - Printa a tela do jogo (apenas AQW e AQLITE). Eles são salvos em uma pasta separada dita abaixo.\n' +
        expand(k.record)    + ' - Grava a tela do jogo. Use de novo para parar.\n' +
        expand(k.reload)    + " - Recarregam as páginas, como em um navegador\n" +
        expand(k.reloadCache)+' - Limpa todo o cachê do jogo, alguns cookies, e recarrega a página (pode consertar bugs dentro do jogo)\n' +
        expand(k.settings)  + ' - Abre a tela de Configurações, para customizar as keybindings.\n' +
        expand(k.reminders) + ' - Abre a tela de Lembretes, para acompanhar quests diárias/semanais por personagem.\n\n' +
        'Para um aqlite antigo/customizado, por favor nomeie ele para "aqlite_old.swf" e o coloque na mesma pasta da executável, dita abaixo!\n\n' +
        'Nota: ' + expand(k.help) + ' Mostra esta mensagem.';
    },
    helpScreenshot     : "Pasta dos prints: ",
    helpAqliteOld      : "Pasta do app para o aqlite_old/aquastar.json (Pode mudar se o usuário mover o aplicativo): ",
    helpCustomKeyPath  : "Outro local para o aquastar.json com keybinds customizadas. Veja o Readme.md para mais ajuda: ",
    
    aboutTitle     : "Sobre o AquaStar, versão: ",
    aboutMessage   : "Aquastar não seria possível sem a ajuda de:",
    aboutDetail    : 
        '133spider (github) por criar o AQLite em si\n' +
        'aquaspy (github)\n' +
        'biglavis (github) Por desenvolver a extensão WikiView\n' +
        'Artix Entertainment (artix.com)\n' +
        'ElectronJs (electronjs.org)\n' +
        'Adobe Flash Player (adobe.com)\n' +
        'VOCÊ! (Sim, Você! Obrigado por seu apoio!)\n\n' +
        'Nota: Este não é um produto oficial da Artix. Artix Entertainment não recomenda o uso por qualquer motivo. Você está usando por sua conta e risco.\n\n' +
        'Você pode dar suas opiniões, contribuir, e seguir o projeto em: ',

    aboutDebug     : "Informações para Debug",
    
    aboutGithubPrompt : "Releases do AquaStar",
    aboutClosePrompt  : "Fechar esse Popup" 
}

exports.menuMessages = {
    menuBackward     : "Voltar",
    menuFoward       : "Avançar",
    menuOtherPages   : "Páginas úteis",
    menuOtherPages2  : "Outras páginas úteis",
    menuSocialMedia  : "Redes sociais",
    menuWiki         : "AQW Wiki",
    menuDesign       : "Design Notes",
    menuBalancePatchNotes: "Balance/Class Patch Notes",
    menuAccount      : "AQW Account",
    menuPortal       : "Portal Battleon",
    menuHeromart     : "Heromart",
    menuDailyGifts   : "Drops Diários",
    menuCalendar     : "Calendário de Eventos",
    menuCharpage     : "Charpages",
    menuForge        : "Encantamentos de Forja",
    menuReddit       : "AQW Subreddit",
    menuTwitter      : "Twitter da Alina",
    menuTakeShot     : "Printa a Charpage (somente CP!)",
    menuCopyURL      : "Copiar o link da página",
    menuReloadPage   : "Recaregar a página",
    menuSettings     : "Configurações",
    menuReminders    : "Lembretes",
    menuTodo         : "Lista de Tarefas",
    menuInventory    : "Inventário",
    menuStrategy     : "Estratégia"
}

exports.settingsMessages = {
    title            : "AquaStar - Configurações",
    heading          : "Configurações de Keybindings",
    description      : "Clique em \"Gravar\" e pressione uma nova combinação de teclas para alterar um atalho. As mudanças são salvas no arquivo mostrado abaixo e exigem reiniciar o AquaStar para terem efeito.",
    saveLocationLabel: "Salvando em: ",
    saveButton       : "Salvar Alterações",
    resetAllButton   : "Restaurar Tudo ao Padrão",
    restartButton    : "Reiniciar o AquaStar Agora",
    closeButton      : "Fechar",
    recordButton     : "Gravar",
    recordingLabel   : "Pressione as teclas... (Esc para cancelar)",
    resetButton      : "Restaurar",
    savedMessage     : "Salvo! Reinicie o AquaStar para aplicar as novas keybindings.",
    macOnlyLabel     : " (somente macOS)",
    charpageOnly     : " (somente char pages)",
    labels: {
        wiki:        "Abrir a Wiki do AQW",
        account:     "Abrir a Página da Conta",
        design:      "Abrir as Design Notes",
        charpage:    "Consultar Char Page",
        newAqw:      "Abrir Nova Instância do AQW",
        newTest:     "Abrir Instância de Testes do AQW",
        about:       "Sobre o AquaStar",
        fullscreen:  "Ativar/Desativar Fullscreen",
        sshot:       "Printar a Janela do Jogo",
        cpSshot:     "Printar a Char Page",
        reload:      "Recarregar a Página",
        reloadCache: "Recarregar e Limpar o Cachê",
        dragon:      "Abrir o DragonFable",
        forward:     "Avançar",
        backward:    "Voltar",
        help:        "Mostrar a Ajuda",
        settings:    "Abrir Configurações (esta tela)",
        reminders:   "Abrir Lembretes",
        todo:        "Abrir Lista de Tarefas",
        inventory:   "Abrir Inventário",
        strategy:    "Abrir Estratégia",
        record:      "Gravar a Tela do Jogo"
    },
    optionsHeading: "Outras Opções",
    optionLabels: {
        playerCharacter:   "Personagem",
        featurePlayerName: "Mostrar Personagem no Título da Janela",
        customUrl:         "URL Customizada do Jogo",
        recordingFormat:   "Formato de Gravação",
        renderMode:        "Renderizador de Flash",
        ruffleUpdateChannel: "Canal de Atualização do Ruffle",
        ruffleAutoUpdate:  "Baixar atualizações automaticamente",
        autoSync:          "Auto Sincronizar Inventário",
        enableDevTools:    "Ativar DevTools"
    },
    optionHints: {
        playerCharacter:   "Apenas letras e números. Usado pelo atalho da Char Page (Alt+P) para abrir direto neste personagem.",
        featurePlayerName: "Quando ativado, substitui \"AquaStar\" no título da janela principal pelo Personagem acima.",
        customUrl:         "Carrega um SWF/URL de jogo diferente ao invés do AQW padrão. Deixe vazio para usar o padrão. Ignorado se um arquivo SWF customizado (abaixo) estiver ativo.",
        recordingFormat:   "Formato do arquivo ao gravar a tela do jogo (Ctrl+J). MP4 não está disponível nesta versão do Electron.",
        renderMode:        "Qual runtime Flash carrega o AQW (principal, nova instância, Testing) e o DragonFable (Alt+1). A Char Page não é afetada (a Artix já usa Ruffle lá).",
        ruffleUpdateChannel: "Latest usa a versão estável mais recente do Ruffle. Nightly inclui mudanças experimentais mais novas. Para aplicar uma troca de canal, feche o AquaStar completamente e abra-o novamente; não use somente o botão Reiniciar.",
        ruffleAutoUpdate:  "Verifica o canal selecionado em segundo plano sempre que o AquaStar abre. O download é aplicado depois de reiniciar.",
        autoSync:          "Sincroniza periodicamente seus dados de Inventário/BuyBack do account.aq.com em segundo plano (a cada ~2 horas), depois de você logar lá pelo menos uma vez via Alt+A. Quando desligado, a sincronização só acontece quando você usa um botão Sincronizar Agora (na janela de Inventário ou no account.aq.com/Home).",
        enableDevTools:    "Abre o console de DevTools automaticamente ao iniciar."
    },
    customSwfHeading      : "Arquivo SWF Customizado",
    customSwfLabel        : "Arquivo SWF Local",
    customSwfHint         : "Substitui o jogo AQW padrão inteiramente por um arquivo .swf local - tem prioridade sobre a URL Customizada do Jogo acima. Só tem efeito depois de reiniciar o AquaStar.",
    customSwfActiveLabel  : "Ativo: ",
    customSwfInactiveLabel: "Não definido - usando o AQW padrão.",
    customSwfChooseButton : "Escolher Arquivo...",
    customSwfRemoveButton : "Remover",
    customSwfRemoveConfirm: "Remover o arquivo SWF customizado? O AquaStar voltará a carregar o AQW padrão depois de reiniciar.",
    customSwfChosenMessage: "Arquivo SWF customizado definido. Reinicie o AquaStar para usá-lo.",
    customSwfRemovedMessage: "Arquivo SWF customizado removido. Reinicie o AquaStar para aplicar.",
    ruffleHeading          : "Atualizações do Ruffle",
    ruffleStatusLabel      : "Ruffle selecionado na inicialização",
    ruffleLoadedLabel      : "Selecionado na inicialização: ",
    ruffleConfiguredChannelLabel: "Canal de atualização configurado: ",
    ruffleLatestLabel      : "Latest (Estável)",
    ruffleNightlyLabel     : "Nightly (Experimental)",
    ruffleFallbackLabel    : "Fallback empacotado: ",
    ruffleInactiveLabel    : "O Ruffle não está ativo; Flash Player está selecionado.\n",
    ruffleDownloadedLabel  : "Versão baixada",
    ruffleBundledLabel     : "Fallback empacotado",
    ruffleUpdateLabel      : "Atualizar Ruffle",
    ruffleUpdateHint       : "Baixa a versão web self-hosted do canal selecionado na release oficial do GitHub do Ruffle. Estável é recomendada; Nightly é experimental. Reinicie para aplicar.",
    ruffleUpdateButton     : "Baixar Atualização",
    ruffleDownloadingMessage: "Baixando atualização do Ruffle...",
    ruffleUpdatedMessage   : "Atualização do Ruffle baixada. Reinicie o AquaStar para aplicar.",
    ruffleAlreadyCurrentMessage: "O Ruffle já está atualizado.",
    ruffleBundledAlreadyCurrentMessage: "O Ruffle empacotado já é a versão estável mais recente.",
    ruffleUpdateFailedMessage: "Não foi possível atualizar o Ruffle: ",
    ruffleRestoreLabel     : "Restaurar Ruffle empacotado",
    ruffleRestoreHint      : "Remove os arquivos de Ruffle baixados no próximo reinício e usa a versão que veio com o AquaStar.",
    ruffleRestoreButton    : "Restaurar Versão Empacotada",
    ruffleRestoreConfirm   : "Restaurar a versão do Ruffle que veio com o AquaStar? Os arquivos de Ruffle baixados serão removidos depois de reiniciar.",
    ruffleRestoreMessage   : "O Ruffle empacotado será restaurado ao reiniciar o AquaStar.",
    optionWarnings: {
        renderMode:     "Ruffle é um emulador de Flash experimental e de código aberto. Pode ser mais lento, menos estável, ou se comportar diferente do Flash Player real, principalmente em salas cheias. Trocar mesmo assim?",
        enableDevTools: "Esta opção é para desenvolvedores. Players normalmente não precisam dela. Ativar mesmo assim?"
    }
}

exports.remindersMessages = {
    title              : "AquaStar - Lembretes",
    heading            : "Lembretes",
    description        : "Acompanhe tarefas diárias e semanais do jogo por personagem. Os resets seguem o horário do servidor da AE (America/New_York) - diário à meia-noite, semanal na virada de quinta para sexta.",
    showCompletedLabel : "Mostrar concluídas",
    showMemberDailiesLabel: "Mostrar lembretes member",
    individualHiddenLabel: "Lista de ocultas individual por personagem",
    serverTimeLabel    : "Horário do Servidor",
    categoryClassLabel : "Classe",
    categoryUltraLabel : "Ultra Bosses",
    categoryOtherLabel : "Outros",
    memberToggleLabel  : "Membro",
    memberBadgeShort   : "★",
    memberBadgeTitle   : "Conteúdo exclusivo para membros",
    seasonalToggleLabel: "Sazonal",
    seasonalSectionLabel: "Sazonais",
    nextFriday13Label  : "Próxima sexta-feira 13: ",
    thisMonthLabel     : "Este Mês",
    monthNames: [
        "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
        "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
    ],
    seasonalEvents: {
        nulgathBirthday: { label: "Aniversário do Nulgath (Jan)",                       short: "JAN" },
        carnival:        { label: "Carnaval / Ano Novo Lunar (Fev)",                    short: "FEV" },
        dageBirthday:    { label: "Aniversário do Dage / Dia da Sorte (Mar)",           short: "MAR" },
        aprilFools:      { label: "Dia da Mentira (Abr)",                               short: "ABR" },
        mayThe4th:       { label: "Star Wars Day - 4 de Maio (Mai)",                    short: "MAI" },
        starFestival:    { label: "Festival das Estrelas / Verão (Jul)",                short: "JUL" },
        kalaSeason:      { label: "Volta às Aulas / Dia da Indonésia (Ago)",            short: "AGO" },
        friday13:        { label: "Sexta-feira 13",                                     short: "S13" },
        pirateDay:       { label: "Dia de Falar Como Pirata / Independência (Set)",     short: "SET" },
        anniversary:     { label: "Mogloween / Aniversário do AQW (Out)",               short: "OUT" },
        blackFriday:     { label: "Black Friday (Nov)",                                 short: "NOV" },
        frostval:        { label: "Frostval / Ano Novo (Dez)",                          short: "DEZ" }
    },
    addCharacterTab    : "+ Adicionar Personagem",
    promptCharacterName: "Nome do personagem:",
    promptOkButton     : "OK",
    promptCancelButton : "Cancelar",
    baseCharacterPrompt: "A lista de ocultas de qual personagem deve virar a nova lista compartilhada?",
    confirmDeleteCharacter: "Remover este personagem e seu progresso em todas as quests? Isso não pode ser desfeito.",
    confirmDeleteQuest : "Excluir esta quest para todos os personagens? Isso não pode ser desfeito.",
    noCharactersHint   : "Adicione uma aba de personagem acima para começar a acompanhar quests.",
    questNamePlaceholder: "Nome da quest",
    questJoinPlaceholder: "/join ...",
    filterNamePlaceholder: "Filtrar por nome...",
    filterAllLabel     : "Todas",
    dailyLabel         : "Diária",
    weeklyLabel        : "Semanal",
    monthlyLabel       : "Mensal",
    addQuestButton     : "Adicionar Quest",
    copyButton         : "Copiar",
    copiedLabel        : "Copiado!",
    deleteButton       : "Excluir",
    hideButton         : "Ocultar",
    unhideButton       : "Reexibir",
    archiveToggleLabel : "Ocultas",
    dragHandleTitle    : "Arraste para reordenar",
    renameTabTitle     : "Renomear",
    removeTabTitle     : "Remover",
    savingLabel        : "Salvando...",
    savedLabel         : "Salvo"
}

exports.todoMessages = {
    title              : "AquaStar - Lista de Tarefas",
    heading            : "Lista de Tarefas",
    description        : "Acompanhe drops, itens de loja e recompensas de quest para pegar, por personagem.",
    serverTimeLabel    : "Horário do Servidor",
    individualHiddenLabel: "Lista de concluídas individual por personagem",
    categoryDropLabel  : "Drop",
    categoryDailyDropLabel: "Drop Diário",
    categoryShopMergeLabel: "Loja/Fusão",
    categoryQuestRewardLabel: "Recompensa de Quest",
    categoryHardFarmLabel: "Farm Difícil",
    categoryReputationFarmLabel: "Farm de Reputação",
    priorityToggleLabel: "Prioridade",
    priorityToggleTitle: "Alternar prioridade - tarefas prioritárias ficam listadas primeiro",
    seasonalToggleLabel: "Sazonal",
    seasonalSectionLabel: "Sazonais",
    nextFriday13Label  : "Próxima sexta-feira 13: ",
    thisMonthLabel     : "Este Mês",
    monthNames: [
        "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
        "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
    ],
    seasonalEvents: {
        nulgathBirthday: { label: "Aniversário do Nulgath (Jan)",                       short: "JAN" },
        carnival:        { label: "Carnaval / Ano Novo Lunar (Fev)",                    short: "FEV" },
        dageBirthday:    { label: "Aniversário do Dage / Dia da Sorte (Mar)",           short: "MAR" },
        aprilFools:      { label: "Dia da Mentira (Abr)",                               short: "ABR" },
        mayThe4th:       { label: "Star Wars Day - 4 de Maio (Mai)",                    short: "MAI" },
        starFestival:    { label: "Festival das Estrelas / Verão (Jul)",                short: "JUL" },
        kalaSeason:      { label: "Volta às Aulas / Dia da Indonésia (Ago)",            short: "AGO" },
        friday13:        { label: "Sexta-feira 13",                                     short: "S13" },
        pirateDay:       { label: "Dia de Falar Como Pirata / Independência (Set)",     short: "SET" },
        anniversary:     { label: "Mogloween / Aniversário do AQW (Out)",               short: "OUT" },
        blackFriday:     { label: "Black Friday (Nov)",                                 short: "NOV" },
        frostval:        { label: "Frostval / Ano Novo (Dez)",                          short: "DEZ" }
    },
    addCharacterTab    : "+ Adicionar Personagem",
    promptCharacterName: "Nome do personagem:",
    promptOkButton     : "OK",
    promptCancelButton : "Cancelar",
    baseCharacterPrompt: "A lista de concluídas de qual personagem deve virar a nova lista compartilhada?",
    confirmDeleteCharacter: "Remover este personagem e seu progresso em todas as tarefas? Isso não pode ser desfeito.",
    confirmDeleteTask  : "Excluir esta tarefa para todos os personagens? Isso não pode ser desfeito.",
    noCharactersHint   : "Adicione uma aba de personagem acima para começar a acompanhar tarefas.",
    taskNamePlaceholder: "Nome da tarefa",
    wikiLinkPlaceholder: "Link da wiki (opcional)",
    joinCommandPlaceholder: "/join ... (opcional)",
    copyButton         : "Copiar",
    copiedLabel        : "Copiado!",
    filterNamePlaceholder: "Filtrar por nome...",
    filterAllLabel     : "Todas",
    addTaskButton      : "Adicionar Tarefa",
    wikiLinkButtonTitle: "Abrir link da wiki",
    completeButton     : "Concluir",
    reopenButton       : "Reabrir",
    deleteButton       : "Excluir",
    completedToggleLabel: "Concluídas",
    dragHandleTitle    : "Arraste para reordenar",
    renameTabTitle     : "Renomear",
    removeTabTitle     : "Remover",
    savingLabel        : "Salvando...",
    savedLabel         : "Salvo"
}

exports.strategyMessages = {
  title: "AquaStar - Estratégia",
  heading: "Estratégia",
  description: "Planeje composições, táticas e mecânicas cronometradas para Ultra e Challenge Bosses.",
  addBoss: "Adicionar Boss",
  manageClasses: "Classes",
  managePotions: "Potes",
  manageTimerTypes: "Tipos de Timer",
  saved: "Salvo",
  emptyBosses: "Nenhum boss cadastrado. Adicione um para começar.",
  emptyStrategies: "Nenhuma estratégia cadastrada.",
  ultra: "Ultra Boss",
  challenge: "Challenge Boss",
  weekly: "Semanal",
  daily: "Diária",
  players: "jogadores",
  zone: "Zona",
  noJoin: "Sem /join definido",
  main: "Boss",
  left: "Esquerda",
  right: "Direita",
  open: "Abrir",
  edit: "Editar",
  delete: "Excluir",
  deleteBossConfirm: "Excluir este boss e todas as estratégias dele?",
  deleteStrategyConfirm: "Excluir esta estratégia?",
  bosses: "Todos os Bosses",
  strategies: "Estratégias",
  addStrategy: "Adicionar Estratégia",
  editStrategy: "Editar Estratégia",
  team: "Composição do Time",
  bossNotes: "Detalhes do Boss",
  strategyNotes: "Detalhes da Estratégia",
  save: "Salvar",
  player: "Jogador",
  noClass: "Nenhuma classe selecionada",
  editBoss: "Editar Boss",
  name: "Nome",
  join: "Comando /join",
  reset: "Reset",
  kind: "Tipo de boss",
  role: "Função",
  cancel: "Cancelar",
  close: "Fechar",
  add: "Adicionar",
  timers: "Timers",
  intro: "Intro (executa uma vez)",
  loop: "Loop (repete)",
  addTimer: "Adicionar Timer",
  delay: "Intervalo (segundos)",
  timerType: "Efeito",
  target: "Alvo",
  assignment: "Função",
  timerLabel: "Nota",
  timerRunner: "Timer ao Vivo",
  startTimer: "Iniciar Timer",
  stopTimer: "Parar Timer",
  timerIdle: "Pronto — inicie o timer para executar a estratégia.",
  shortcut: "Atalho global de alternância (com esta estratégia aberta)",
  shortcutError: "Atalho indisponível",
  potionKind: "Categoria",
  tonic: "Tônico",
  elixir: "Elixir",
  potion: "Pote",
  timerRoles: "Funcões de Timer",
  timerRolesHelp: "Cada função tem seu próprio atraso inicial e intervalo de repetição. A ação acontece ao fim da barra.",
  addRole: "Adicionar função",
  showRoles: "Mostrar funções",
  all: "Todos",
  none: "Nenhum",
  bestTonic: "Melhor tônico",
  bestElixir: "Melhor elixir",
  noPreference: "Sem preferência",
  saveClass: "Salvar classe",
  generalBossInfo: "Informações gerais do boss",
  generalBossInfoHint: "Exibido somente para leitura nas estratégias deste boss",
  consumables: "Consumíveis",
  consumablesFor: "Consumíveis de",
  noFavoriteConsumables: "Nenhum tônico ou elixir favorito configurado para esta classe.",
  noConsumablesInInventory: "Nenhum consumível desta classe está no inventário sincronizado.",
  actionIn: "Ação em",
  functionLabel: "Função",
  roles: {
    support: "Suporte",
    dps: "DPS",
    tank: "Tank",
    dot: "Dano ao Longo do Tempo (DoT)"
  }
}

exports.inventoryMessages = {
  title: "AquaStar - Inventário",
  heading: "Inventário",
  description: "Navegue pelos dados de Inventário e BuyBack sincronizados do account.aq.com, por personagem.",
  inventoryTabLabel: "Inventário",
  buyBackTabLabel: "Buy Back",
  syncButton: "Sincronizar Agora",
  syncingLabel: "Sincronizando...",
  syncedLabel: "Última sincronização: ",
  justNowLabel: "agora mesmo",
  neverSyncedLabel: "Nunca sincronizado",
  syncErrorUnauthenticated: "Não está logado. Abra a Página da Conta (Alt+A) e faça login, depois tente de novo.",
  syncErrorNetwork: "Não foi possível acessar account.aq.com. Verifique sua conexão e tente de novo.",
  filterNamePlaceholder: "Buscar itens...",
  filterTypeAll: "Todos os Tipos",
  filterAllLabel: "Todos",
  filterBankLabel: "Apenas no banco",
  filterInventoryOnlyLabel: "Apenas no inventário",
  filterMemberLabel: "Apenas member",
  filterNonMemberOnlyLabel: "Apenas não member",
  filterAcLabel: "Apenas AC",
  filterNonAcLabel: "Apenas não AC",
  emptyStateLabel: "Nenhum item encontrado. Tente sincronizar ou ajustar os filtros.",
  noCharactersLabel: "Nenhum personagem sincronizado ainda. Logue via Alt+A e depois Sincronize Agora.",
  columnName: "Nome",
  columnType: "Tipo",
  columnCount: "Quantidade",
  columnBank: "Banco",
  columnAdded: "Adicionado",
  columnCost: "Custo",
  columnRarity: "Raridade",
  columnInserted: "Vendido",
  bankBadge: "Banco",
  inventoryBadge: "Inventário",
  acBadge: "AC",
  normalBadge: "Normal",
  filterLabels: "Etiquetas",
  labelsSelected: "selecionadas",
  labelFilterClear: "Limpar",
  manageLabels: "Gerenciar Etiquetas",
  labelName: "Nome da etiqueta",
  addLabel: "Adicionar",
  saveLabel: "Salvar",
  assignLabels: "Atribuir Etiquetas",
  labelScopeCharacter: "Este personagem",
  labelScopeGlobal: "Todos os personagens",
  labelScopeCharacterHint: "Aplica apenas ao personagem ativo.",
  labelScopeGlobalHint: "Aplica ao mesmo item para todos os personagens.",
  assignLabelsHint: "O escopo é definido ao criar a etiqueta. Etiquetas de personagem são independentes; etiquetas globais sempre valem para todos.",
  delete: "Excluir",
  close: "Fechar",
  cancel: "Cancelar",
  itemCountLabel: "{shown} de {total} itens"
}

exports.wikiMessages = {
    mergeMaterialsTitle: "AquaStar: Materiais da loja",
    mergeDependencies: "Incluir dependências",
    mergeBuyback: "Dependências com Buy Back",
    mergeEmpty: "Nenhum material listado.",
    mergeReputationLabel: "Reputação necessária:",
    mergeSelectAll: "Marcar todos",
    mergeClearAll: "Desmarcar todos",
    mergeSelectItem: "Selecionar item"
}
