function expand (keyb) {if(Array.isArray(keyb)) return keyb.join(', '); else return keyb;};

exports.titleMessages = {
    invalidCharpage  : "",
    loadingCharpage  : "",
    buildingCharpage : "",
    cpDone           : "",
    doneSavedAs      : "",
    recording        : "", // Please, dont use '!'s
    alreadyRecording : ""
}

exports.charPageStudioMessages = {
    locale: '', title: '', heading: '', description: '', sceneModeLabel: '', charPageMode: '', emptySceneMode: '', emptySceneHint: '',
    characterLabel: '', loadCharacterButton: '', characterHint: '', colorsLabel: '', backgroundIndexLabel: '', emptySceneSettingsLabel: '',
    solidBackgroundLabel: '', nativeFps: '', loadSceneButton: '', savePngButton: ''
}

exports.dialogMessages = {
    helpTitle   :'Help:',
    helpMessage : "",
    helpDetail(k) {return expand(k.wiki) + ' - \n' +
        expand(k.design)    + ' - \n' +
        expand(k.account)   + ' - \n' +
        expand(k.charpage)  + ' - \n' +
        expand(k.cpSshot)   + ' - \n' +
        expand(k.newAqw)    + ' - \n' +
        expand(k.newTest)   + ' - \n' +
        expand(k.about)     + ' - \n' +
        expand(k.fullscreen)+ ' - \n' +
        expand(k.sshot)     + ' - \n' +
        expand(k.record)    + ' - \n' +
        expand(k.reload)    + " - \n" +
        expand(k.reloadCache)+' - \n' +
        expand(k.settings)  + ' - .\n' +
        expand(k.reminders) + ' - .\n\n' +
        '\n\n' +
        ':' + expand(k.help) + ' .';
    },
    helpScreenshot     : ": ",
    helpAqliteOld      : ": ",
    helpCustomKeyPath  : ": ",
    
    aboutTitle     : "",
    aboutMessage   : "",
    aboutDetail    : "",
    aboutDebug     : "",
    
    aboutGithubPrompt : "",
    aboutClosePrompt  : ""
}

exports.menuMessages = {
    menuBackward     : "",
    menuFoward       : "",
    menuOtherPages   : "",
    menuOtherPages2  : "",
    menuSocialMedia  : "",
    menuWiki         : "",
    menuDesign       : "",
    menuBalancePatchNotes: "",
    menuAccount      : "",
    menuPortal       : "",
    menuHeromart     : "",
    menuDailyGifts   : "",
    menuCalendar     : "",
    menuCharpage     : "",
    menuForge        : "",
    menuReddit       : "",
    menuTwitter      : "",
    menuTakeShot     : "",
    menuCopyURL      : "",
    menuReloadPage   : "",
    menuSettings     : "",
    menuReminders    : "",
    menuTodo         : "",
    menuInventory    : "",
    menuStrategy     : ""
}

exports.settingsMessages = {
    title            : "",
    heading          : "",
    description      : "",
    saveLocationLabel: "",
    saveButton       : "",
    resetAllButton   : "",
    restartButton    : "",
    closeButton      : "",
    recordButton     : "",
    recordingLabel   : "",
    resetButton      : "",
    savedMessage     : "",
    macOnlyLabel     : "",
    charpageOnly     : "",
    labels: {
        wiki:        "",
        account:     "",
        design:      "",
        charpage:    "",
        newAqw:      "",
        newTest:     "",
        about:       "",
        fullscreen:  "",
        sshot:       "",
        cpSshot:     "",
        reload:      "",
        reloadCache: "",
        dragon:      "",
        forward:     "",
        backward:    "",
        help:        "",
        settings:    "",
        reminders:   "",
        todo:        "",
        inventory:   "",
        strategy:    "",
        record:      ""
    },
    optionsHeading: "",
    optionLabels: {
        playerCharacter:   "",
        featurePlayerName: "",
        customUrl:         "",
        recordingFormat:   "",
        renderMode:        "",
        autoSync:          "",
        enableDevTools:    ""
    },
    optionHints: {
        playerCharacter:   "",
        featurePlayerName: "",
        customUrl:         "",
        recordingFormat:   "",
        renderMode:        "",
        autoSync:          "",
        enableDevTools:    ""
    },
    customSwfHeading      : "",
    customSwfLabel        : "",
    customSwfHint         : "",
    customSwfActiveLabel  : "",
    customSwfInactiveLabel: "",
    customSwfChooseButton : "",
    customSwfRemoveButton : "",
    customSwfRemoveConfirm: "",
    customSwfChosenMessage: "",
    customSwfRemovedMessage: "",
    ruffleHeading          : "",
    ruffleStatusLabel      : "",
    ruffleLoadedLabel      : "",
    ruffleConfiguredChannelLabel: "",
    ruffleLatestLabel      : "",
    ruffleNightlyLabel     : "",
    ruffleFallbackLabel    : "",
    ruffleInactiveLabel    : "",
    ruffleDownloadedLabel  : "",
    ruffleBundledLabel     : "",
    ruffleUpdateLabel      : "",
    ruffleUpdateHint       : "",
    ruffleUpdateButton     : "",
    ruffleDownloadingMessage: "",
    ruffleUpdatedMessage   : "",
    ruffleAlreadyCurrentMessage: "",
    ruffleBundledAlreadyCurrentMessage: "",
    ruffleUpdateFailedMessage: "",
    ruffleRestoreLabel     : "",
    ruffleRestoreHint      : "",
    ruffleRestoreButton    : "",
    ruffleRestoreConfirm   : "",
    ruffleRestoreMessage   : "",
    optionWarnings: {
        renderMode:     "",
        enableDevTools: ""
    }
}

exports.remindersMessages = {
    title              : "",
    heading            : "",
    description        : "",
    showCompletedLabel : "",
    showMemberDailiesLabel: "",
    individualHiddenLabel: "",
    serverTimeLabel    : "",
    categoryClassLabel : "",
    categoryUltraLabel : "",
    categoryOtherLabel : "",
    memberToggleLabel  : "",
    memberBadgeShort   : "",
    memberBadgeTitle   : "",
    seasonalToggleLabel: "",
    seasonalSectionLabel: "",
    nextFriday13Label  : "",
    thisMonthLabel     : "",
    monthNames: ["", "", "", "", "", "", "", "", "", "", "", ""],
    seasonalEvents: {
        nulgathBirthday: { label: "", short: "" },
        carnival:        { label: "", short: "" },
        dageBirthday:    { label: "", short: "" },
        aprilFools:      { label: "", short: "" },
        mayThe4th:       { label: "", short: "" },
        starFestival:    { label: "", short: "" },
        kalaSeason:      { label: "", short: "" },
        friday13:        { label: "", short: "" },
        pirateDay:       { label: "", short: "" },
        anniversary:     { label: "", short: "" },
        blackFriday:     { label: "", short: "" },
        frostval:        { label: "", short: "" }
    },
    addCharacterTab    : "",
    promptCharacterName: "",
    promptOkButton     : "",
    promptCancelButton : "",
    baseCharacterPrompt: "",
    confirmDeleteCharacter: "",
    confirmDeleteQuest : "",
    noCharactersHint   : "",
    questNamePlaceholder: "",
    questJoinPlaceholder: "",
    filterNamePlaceholder: "",
    filterAllLabel     : "",
    dailyLabel         : "",
    weeklyLabel        : "",
    monthlyLabel       : "",
    addQuestButton     : "",
    copyButton         : "",
    copiedLabel        : "",
    deleteButton       : "",
    hideButton         : "",
    unhideButton       : "",
    archiveToggleLabel : "",
    dragHandleTitle    : "",
    renameTabTitle     : "",
    removeTabTitle     : "",
    savingLabel        : "",
    savedLabel         : ""
}

exports.todoMessages = {
    title              : "",
    heading            : "",
    description        : "",
    serverTimeLabel    : "",
    individualHiddenLabel: "",
    categoryDropLabel  : "",
    categoryDailyDropLabel: "",
    categoryShopMergeLabel: "",
    categoryQuestRewardLabel: "",
    categoryHardFarmLabel: "",
    categoryReputationFarmLabel: "",
    priorityToggleLabel: "",
    priorityToggleTitle: "",
    seasonalToggleLabel: "",
    seasonalSectionLabel: "",
    nextFriday13Label  : "",
    thisMonthLabel     : "",
    monthNames: ["", "", "", "", "", "", "", "", "", "", "", ""],
    seasonalEvents: {
        nulgathBirthday: { label: "", short: "" },
        carnival:        { label: "", short: "" },
        dageBirthday:    { label: "", short: "" },
        aprilFools:      { label: "", short: "" },
        mayThe4th:       { label: "", short: "" },
        starFestival:    { label: "", short: "" },
        kalaSeason:      { label: "", short: "" },
        friday13:        { label: "", short: "" },
        pirateDay:       { label: "", short: "" },
        anniversary:     { label: "", short: "" },
        blackFriday:     { label: "", short: "" },
        frostval:        { label: "", short: "" }
    },
    addCharacterTab    : "",
    promptCharacterName: "",
    promptOkButton     : "",
    promptCancelButton : "",
    baseCharacterPrompt: "",
    confirmDeleteCharacter: "",
    confirmDeleteTask  : "",
    noCharactersHint   : "",
    taskNamePlaceholder: "",
    wikiLinkPlaceholder: "",
    joinCommandPlaceholder: "",
    copyButton         : "",
    copiedLabel        : "",
    filterNamePlaceholder: "",
    filterAllLabel     : "",
    addTaskButton      : "",
    wikiLinkButtonTitle: "",
    completeButton     : "",
    reopenButton       : "",
    deleteButton       : "",
    completedToggleLabel: "",
    dragHandleTitle    : "",
    renameTabTitle     : "",
    removeTabTitle     : "",
    savingLabel        : "",
    savedLabel         : ""
}

exports.strategyMessages = {
  title: "",
  heading: "",
  description: "",
  addBoss: "",
  manageClasses: "",
  managePotions: "",
  manageTimerTypes: "",
  saved: "",
  emptyBosses: "",
  emptyStrategies: "",
  ultra: "",
  challenge: "",
  weekly: "",
  daily: "",
  players: "",
  zone: "",
  noJoin: "",
  main: "",
  left: "",
  right: "",
  open: "",
  edit: "",
  delete: "",
  deleteBossConfirm: "",
  deleteStrategyConfirm: "",
  bosses: "",
  strategies: "",
  addStrategy: "",
  editStrategy: "",
  team: "",
  bossNotes: "",
  strategyNotes: "",
  save: "",
  player: "",
  noClass: "",
  editBoss: "",
  name: "",
  join: "",
  reset: "",
  kind: "",
  role: "",
  cancel: "",
  close: "",
  add: "",
  timers: "",
  intro: "",
  loop: "",
  addTimer: "",
  delay: "",
  timerType: "",
  target: "",
  assignment: "",
  timerLabel: "",
  timerRunner: "",
  startTimer: "",
  stopTimer: "",
  timerIdle: "",
  shortcut: "",
  shortcutError: "",
  potionKind: "",
  tonic: "",
  elixir: "",
  potion: "",
  timerRoles: "",
  timerRolesHelp: "",
  addRole: "",
  showRoles: "",
  all: "",
  none: "",
  bestTonic: "",
  bestElixir: "",
  noPreference: "",
  saveClass: "",
  generalBossInfo: "",
  generalBossInfoHint: "",
  consumables: "",
  consumablesFor: "",
  noFavoriteConsumables: "",
  noConsumablesInInventory: "",
  actionIn: "",
  functionLabel: "",
  roles: {
    support: "",
    dps: "",
    tank: "",
    dot: ""
  }
}

exports.inventoryMessages = {
    title              : "",
    heading            : "",
    description        : "",
    inventoryTabLabel  : "",
    buyBackTabLabel    : "",
    syncButton         : "",
    syncingLabel       : "",
    syncedLabel        : "",
    justNowLabel       : "",
    neverSyncedLabel   : "",
    syncErrorUnauthenticated: "",
    syncErrorNetwork  : "",
    filterNamePlaceholder: "",
    filterTypeAll      : "",
    filterAllLabel     : "",
    filterBankLabel    : "",
    filterInventoryOnlyLabel: "",
    filterMemberLabel  : "",
    filterNonMemberOnlyLabel: "",
    filterAcLabel      : "",
    filterNonAcLabel   : "",
    emptyStateLabel    : "",
    noCharactersLabel  : "",
    columnName         : "",
    columnType         : "",
    columnCount        : "",
    columnBank         : "",
    columnAdded        : "",
    columnCost         : "",
    columnRarity       : "",
    columnInserted     : "",
    bankBadge          : "",
    inventoryBadge     : "",
    acBadge            : "",
    normalBadge        : "",
    filterLabels: "",
    labelsSelected: "",
    labelFilterClear: "",
    manageLabels: "",
    labelName: "",
    addLabel: "",
    saveLabel: "",
    assignLabels: "",
    labelScopeCharacter: "",
    labelScopeGlobal: "",
    labelScopeCharacterHint: "",
    labelScopeGlobalHint: "",
    assignLabelsHint: "",
    delete: "",
    close: "",
    cancel: "",
    itemCountLabel: ""    
}

exports.wikiMessages = {
    mergeMaterialsTitle: "",
    mergeDependencies: "",
    mergeBuyback: "",
    mergeEmpty: "",
    mergeReputationLabel: "",
    mergeSelectAll: "",
    mergeClearAll: "",
    mergeSelectItem: ""
}
