exports.helpTitle = ""
exports.helpMessage = ""
exports.helpDetail = ""
exports.helpScreenshot = ""
exports.helpAqliteOld  = ""
exports.aboutTitle = ""
exports.aboutMessage = ""
exports.aboutDetail = ""
