const assert = require('assert');
const fs = require('fs');
const path = require('path');

test('Char Page Studio loads an explicitly requested Char Page into native Flash controls', () => {
    const lab = fs.readFileSync(path.join(__dirname, '../../res/features/charpage/lab/characterB-lab.html'), 'utf8');
    ['player-name', 'load-character', 'initialFlashVars = \'\'', 'colorDefinitions', 'intColorHair', 'intColorSkin', 'intColorEye', 'intColorBase', 'intColorTrim', 'intColorAccessory', 'studioVisibilityDefinitions', 'studioShowIdentity', 'studioShowProfileButton', 'studioShowCosmeticsButton', 'studioShowBackground', 'studioShowBorder', 'show-weapon', 'items/swords/unarmed.swf', 'strCustWeaponFile', 'bgindex', 'max="31"', 'studioApi.loadCharacter', 'studioApi.getDefaults', 'studioApi.capturePreview', 'studioApi.getRuntimeStatus', 'Salvar print PNG', 'Abrir DevTools', 'diagnostics', 'application/x-shockwave-flash', 'FlashVars', "flashVarString = '&' + parameters.toString()", 'Opções avançadas', 'Classe e armadura', 'Cabelo e elmo', 'Armas', 'Pet e cenário', 'function changeParam', 'function removeParam', 'sidebar-controls', 'preview-pane', 'align-items: flex-start', 'function resizePreview', 'nativeMovieWidth = 715', 'nativeMovieHeight = 455', "window.addEventListener('resize', resizePreview)"].forEach((fragment) => {
        assert.ok(lab.indexOf(fragment) !== -1, 'laboratory must contain ' + fragment);
    });
    assert.ok(lab.indexOf('if (!currentSourceUrl || !flashvars.value)') !== -1);
    assert.ok(lab.indexOf('function writeParams(params, advancedGroup)') !== -1);
    assert.ok(lab.indexOf('function syncDirectControls(params)') !== -1);
    assert.ok(lab.indexOf('function renderAdvancedGroup(title, params)') !== -1);
    const writeParamsBody = lab.slice(lab.indexOf('function writeParams'), lab.indexOf('function changeParam'));
    assert.ok(writeParamsBody.indexOf('syncControls(params)') === -1, 'ordinary field edits must not rebuild every advanced group');
    assert.ok(lab.indexOf("writeParams(params, 'Armas')") !== -1, 'weapon toggle refreshes only its own advanced group');
    const bridge = fs.readFileSync(path.join(__dirname, '../../res/features/charpage/studio.js'), 'utf8');
    const config = fs.readFileSync(path.join(__dirname, '../../res/windows/config.js'), 'utf8');
    const instances = fs.readFileSync(path.join(__dirname, '../../res/instances.js'), 'utf8');
    const menu = fs.readFileSync(path.join(__dirname, '../../res/windows/menu.js'), 'utf8');
    const main = fs.readFileSync(path.join(__dirname, '../../main.js'), 'utf8');
    assert.ok(bridge.indexOf("charpage-studio-load-character") !== -1);
    assert.ok(bridge.indexOf("charpage-studio-capture") !== -1);
    assert.ok(bridge.indexOf("charpage-studio-open-devtools") !== -1);
    assert.ok(bridge.indexOf("charpage-studio-runtime-status") !== -1);
    assert.ok(bridge.indexOf('extractCharPageData') !== -1);
    assert.ok(bridge.indexOf("'characterB-studio.swf'") !== -1, 'Studio uses its packaged SWF');
    assert.ok(bridge.indexOf("studioAssetBaseUrl") !== -1, 'local Studio SWF receives its AQW asset root');
    assert.ok(bridge.indexOf("interceptBufferProtocol") === -1, 'Studio must not replace the default HTTPS session');
    assert.ok(bridge.indexOf('.filterResponseData(') === -1, 'Electron 11 does not provide filterResponseData');
    assert.ok(config.indexOf('charPageStudioConfig') !== -1);
    assert.ok(config.indexOf('plugins: true') !== -1);
    assert.ok(config.indexOf('sandbox: false') !== -1);
    assert.ok(config.indexOf('studio.deactivateProtocol()') !== -1);
    assert.ok(instances.indexOf('openCharPageStudioWindow') !== -1);
    assert.ok(menu.indexOf('menuCharPageStudio') !== -1);
    assert.ok(main.indexOf("require('./res/features/charpage/studio.js')") !== -1);
    const studioSwf = fs.readFileSync(path.join(__dirname, '../../res/features/charpage/characterB-studio.swf'));
    assert.ok(['CWS', 'FWS'].indexOf(studioSwf.slice(0, 3).toString('ascii')) !== -1, 'bundled Studio asset must be a valid SWF');
    assert.ok(lab.indexOf("var movieUrl = currentSourceUrl + '?v=2&' + parameters.toString()") !== -1, 'pass FlashVars through the movie URL for Pepper Flash');
    assert.ok(lab.indexOf("player.setAttribute('flashvars', flashVarString)") !== -1, 'pass FlashVars directly to the PPAPI embed');
    assert.ok(lab.indexOf('player.src = movieUrl') > lab.indexOf("player.setAttribute('flashvars', flashVarString)"), 'set FlashVars before the native plugin source');
    assert.ok(config.indexOf("on('new-window'") !== -1);
    assert.ok(config.indexOf('webContents.setWindowOpenHandler(') === -1);
});
