name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run dist-l
      - uses: actions/upload-artifact@v4
        with:
          name: aquastar-linux-x64
          path: |
            dist/*.AppImage
            dist/*.deb
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run dist-w
      - uses: actions/upload-artifact@v4
        with:
          name: aquastar-windows-x64
          path: |
            dist/*.exe
          if-no-files-found: error

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run dist-m
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
      - uses: actions/upload-artifact@v4
        with:
          name: aquastar-macos-x64
          path: |
            dist/*.dmg
            dist/*.zip
          if-no-files-found: error